all: commands
	g++ -o kash main.cpp include/inbuilds.cpp

commands:

	g++ -o ~/bin/kcat src/cat.cpp
	g++ -o ~/bin/kstat src/file_information.cpp
	g++ -o ~/bin/kls src/list.cpp
	g++ -o ~/bin/kmkdir src/make_directory.cpp
	g++ -o ~/bin/kmove src/move.cpp
	g++ -o ~/bin/krm src/remove.cpp
	g++ -o ~/bin/ktime src/time.cpp
	g++ -o ~/bin/ktouch src/touch.cpp


clear:
	rm kash